---
title: "Week8"
author: "Puneeth"
date: "March 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
##install.packages("factoextra")
library(rvest)
library(ggplot2)
library(cluster)


urlfile <- read_html("http://carsalesbase.com/us-car-sales-data/acura/")
carmodel <- html_table(urlfile, header=TRUE)[[2]]
colnames(carmodel)[1] <- "Year"
df<-data.frame(carmodel)
df

ggplot(df, aes(x=Year, y=Acura..All.Models, color = Year)) +
   geom_point(shape=1)  

set.seed(20)
irisCluster <- kmeans(df[, 1:2], 3, nstart = 20)
irisCluster

centers=as.data.frame(irisCluster$centers)


table(irisCluster$cluster, df$Year)


irisCluster$cluster <- as.factor(irisCluster$cluster)
ggplot(df, aes(Year, Acura..All.Models, color = irisCluster$cluster)) + geom_point() + geom_point(data=centers, aes(x=Year,y=Acura..All.Models, color='Center'), shape = 3) +
geom_point(data=centers, aes(x=Year,y=Acura..All.Models, color='Center'), size=52, alpha=.3, legend=FALSE)










```

