---
title: "Week2"
author: "Puneeth"
date: "January 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.Sequences of Numbers
```{r}
firstseq <- 1:20    #Sequences of 1 to 20
print(firstseq)

secondseq <- 21:40  #Sequences of 21 to 40
print(secondseq)

thirdseq <- 41:60   #Sequences of 41 to 60
print(thirdseq)

fourthseq <- 1:100  #Sequences of 1 to 100
print(fourthseq)

class(firstseq)   #names the datatype of object
```

2.Vectors
```{r}
firstvector <- c("Omaha", 10, 16, 8, 30, 70)           #data for firstvector
secondvector <- c("Western", 22, 18, 22, 16, 78)       #data for secondvector

print(firstvector)
print(secondvector)

print(firstvector[3])    #print 3rd element of firstvector
print(secondvector[1])   #print 1st element of secondvector

length(firstvector)     #length of firstvector
length(secondvector)    #length of secondvector

for(x in firstvector){      #for each number to be printed
  print(x)
}

firstvector[3] <- 30       # modify 3rd element
print(firstvector)
secondvector[2] <- 11      # modify 2nd element
print(secondvector)

```

3.Missing Values
```{r}
x <- c("Spurs", 28, 32, 36, NA ,30, 126)
y <- c("Pelicans", 27, 30, 28, 29, NA, 114)

is.na(x)      #find where na is?
is.na(y)      #find where na is?

is.nan(x)     #find where nan is?
is.nan(y)     #find where nan is?

which(is.na(x))   # Which one is NA?
which(is.na(y))   # Which one is NA?

sum(is.na(x))     # Sum of na in vector
sum(is.na(y))     # sum of na in vector

na.exclude(x)   #exludes na value
na.exclude(y)   #excludes na value

e <- data.frame (x, y)  # data frame with missing values
e


```

4.Subsetting Vectors
```{r}
f <- c("suns", 32, 23, 26 ,  NA, 95)
g <- c("Nuggets", 37, 33, 28, NA, 97)

f[1]
g[2]
f[1:4]
f[f > 30]
u <- g > 40
u
g[u]

good <- list(foo = c("suns", 32, 23, 26 ,14, NA, 95), bar = c("Nuggets", 37, 33, 28, NA, 34, 97))

good[1]
good[[1]]
good$bar

bad <- complete.cases(f, g)
bad
f[bad]
g[bad]

```

5.Matrices and Data Frame
```{r}
a <- c("76ers", 37, 31, 28 ,14, 110)
b <- c("Nuggets", 41, 36, 30, 19, 126)

dim(a) <- c(2,3)  #change to dim matrix 2x3
dimnames(a) <- list(c("X","Y"), c("A","B","C")) # name the rows and columns
a
dim(b) <- c(2,3)   #change to dim matrix 2x3
dimnames(b) <- list(c("A","B"), c("X","Y","Z")) # name the rows and columns
b


cbind(a, b) # combine columns
rbind(a, b) # combine rows

data.matrix(a) # create matrix using data frame
data.matrix(b) # create matrix using data frame

d <- data.frame(a, b) # create a data frame
d

a["X","A"] <- 20 #modify a Data Frame
a
b["B","Y"] <- 22
b
```

